server:
  port: 8085

spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/boardiox_db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.azobioz.notification.event,com.azobioz.board.event"
я
logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
