server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/board_db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
board:
  size:
    x: 1000
    y: 1000



